#!/bin/bash

cert_name=$(basename ${RENEWED_LINEAGE} | sed 's/\./-/')-$(date +%Y-%m%d-%H%M)

# these values might be better handled in the .oci/config
load_balancer_id=<id string>
listener_name=<load balancer public listener>
backend_set_name=<load balancer bakend set (pool)>

oci lb certificate create \
	--load-balancer-id ${load_balancer_id} \
	--certificate-name ${cert_name} \
	--public-certificate-file ${RENEWED_LINEAGE}/fullchain.pem \
	--private-key-file ${RENEWED_LINEAGE}/privkey.pem \
	--wait-for-state SUCCEEDED \
	> /tmp/${cert_name}_create.json

oci lb listener update \
	--load-balancer-id ${load_balancer_id} \
	--ssl-certificate-name ${cert_name} \
	--listener-name ${listener_name} \
	--default-backend-set-name ${backend_set_name} \
	--port 443 \
	--protocol TCP \
	--force \
	--wait-for-state SUCCEEDED \
	> /tmp/${cert_name}_use.json
