#!/bin/bash

cert_name=$(basename ${RENEWED_LINEAGE} | sed 's/\./-/')-$(date +%Y-%m%d-%H%M)
load_balancer_id=ocid1.loadbalancer.oc1.eu-zurich-1.aaaaaaaaznk2gcae3kgoq6vvcacft2i4uod6jtwpujdw3mnrg4cdp2irfdgq
listener_name=listener_lb_2025-1101-1341
backend_set_name=bs_lb_2025-1101-1341

oci lb certificate create \
	--load-balancer-id ${load_balancer_id} \
	--certificate-name ${cert_name} \
	--public-certificate-file ${RENEWED_LINEAGE}/fullchain.pem \
	--private-key-file ${RENEWED_LINEAGE}/privkey.pem \
	--wait-for-state SUCCEEDED

oci lb listener update \
	--load-balancer-id ${load_balancer_id} \
	--ssl-certificate-name ${cert_name} \
	--listener-name ${listener_name} \
	--default-backend-set-name ${backend_set_name} \
	--port 443 \
	--protocol TCP \
	--force \
	--wait-for-state SUCCEEDED
