#!/bin/bash

cert_name=$(basename ${RENEWED_LINEAGE} | sed 's/\./-/')-$(date +%Y-%m%d-%H%M)

# these values might be better handled in the .oci/config
load_balancer_id=<id string>
listener_name=<load balancer public listener>
backend_set_name=<load balancer bakend set (pool)>

oci lb certificate create \
	--load-balancer-id ${load_balancer_id} \
	--certificate-name ${cert_name} -test \
	--public-certificate-file ${RENEWED_LINEAGE}/fullchain.pem
	--private-key-file ${RENEWED_LINEAGE}/fullchain.pem

# TODO: check for errors

oci lb listener update \
	--load-balancer-id ${load_balancer_id} \
	--ssl-certificate-name ${cert_name} \
	--listener-name ${listener_name} \
	--default-backend-set-name ${backend_set_name} \
	--port 443 \
	--protocol TCP

# TODO: check for errors
#
# We should poentially raise an alarm to the console if either of these two
# operations fail
